### ISSUE TITLE
Multiple Atomico versions installed

### ISSUE THREAD

**Issue by efoken** [atomicojs/lit-html#1]
@UpperCod remember? We had this problem a while ago.

In many of your packages you set `atomico@latest` as a hard dependency instead of putting it to peerDependencies.

Some lines from our yarn.lock file:

```yml
"@atomico/lit-html@^1.0.0":
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/@atomico/lit-html/-/lit-html-1.0.0.tgz#9e842692ba86b40b48b19cab0586b3755e204927"
  integrity sha512-5uD28vvgjmDmrdu6FYukPwMrzGYVHujb/3kPgwp3PigaRSZSDTK89t+O+b7YAYhC76SMPUV6xFS+JAQMx59W5A==
  dependencies:
    atomico latest
    lit-html latest

"@atomico/storybook@^1.0.7":
  version "1.0.7"
  resolved "https://registry.yarnpkg.com/@atomico/storybook/-/storybook-1.0.7.tgz#dbba9268003af1fbd554f5f986e411f08cdf5d58"
  integrity sha512-abfAVKQ19UEU9T/B0+Psa4V/2nFYE9KzzT16KXFp7LPXd6lMnGQ1znjioXobiN6SUIziJD9e1TV91udorw+77A==
  dependencies:
    "@storybook/csf" latest
    atomico latest
```

Better would always be using the following instead of putting to `dependencies`:

```json
"peerDependencies": {
  "atomico": "*"
},
"devDependencies": {
  "atomico": "latest"
}
```

**Comment by efoken** [comment]
Same for `lit-html`, Storybook gives a warning in console that multiple versions of Lit are installed.

**Comment by UpperCod** [comment]
Interesting, I have released a new version `@atomico/lit-html@1.1.1`, but in this one I maintain the use of dependencies and peerDependencies, but I have defined peerDependencies as any.

for the next version I will test how pnpm and yarn process the dependencies to see if we can publish them as you comment

**Comment by efoken** [comment]
It is not fine like it is now, you have to remove peerDependencies from the dependencies and instead put them to devDependencies

**Comment by efoken** [comment]
Currently:

```json
    "dependencies": {
        "atomico": "^1.65.0",
        "lit-html": "*"
    },
    "peerDependencies": {
        "atomico": "*",
        "lit-html": "*"
    },
    "devDependencies": {
        ...
    },
```

But correct would be:

```json
    "dependencies": {
    },
    "peerDependencies": {
        "atomico": "*",
        "lit-html": "*"
    },
    "devDependencies": {
        "atomico": "latest",
        "lit-html": "latest",
        ...
    },
```

**Comment by UpperCod** [comment]
👋 @atomico/lit-html@1.2.0 I have fixed the types and dependencies of this package

**Comment by efoken** [comment]
Works perfectly now, thank you 👍 (also the exports)
